
(write (first '(p h w)))
(write-line "")
(write (rest '(p k p h)))
(write-line "")
(write (first '((a b)(c d))))
(write-line "")
(write (rest '((a b ) (c d))))
(write-line "")
(write (first(rest '((a b)(c d)))))
(write-line "")
(write (rest(first '((a b)(c d)))))
(write-line "")
(write (rest(first(rest '((a b)(c d))))))
(write-line "")
(write (first(rest(first '((a b)(c d))))))
